const endpoints = {
    login: "/auth",
    register: "/users",
    profile: "/secure/profile",
    usersManagement: "/secure/manager/users",
    userManagement: (userId: string | number) => `/secure/manager/users/${userId}`,
    crops: "/crops",
    cropsManagement: "/secure/manager/crops",
    cropManagement: (cropId: string | number) => `/secure/manager/crops/${cropId}`,
    seasons: "/seasons",
    season: (seasonId: string | number) => `/seasons/${seasonId}`,
    seasonsManagement: "/secure/manager/seasons",
    seasonManagement: (seasonId: string | number) => `/secure/manager/seasons/${seasonId}`,
    tasksManagement: "/secure/manager/tasks",
    taskManagement: (taskId: string | number) => `/secure/manager/tasks/${taskId}`,
    myTasks: "/secure/tasks",
    taskCompletions: "/secure/task-completions",
    taskCompletionManagement: (taskCompletionId: string | number) => `/secure/task-completions/${taskCompletionId}`,
    plots: "/secure/plots",
    plotManagement: (plotId: string | number) => `/secure/plots/${plotId}`,
    articles: "/articles",
    article: (articleId: string | number) => `/articles/${articleId}`,
    articlesManagement: "/secure/articles",
    articleManagement: (articleId: string | number) => `/secure/articles/${articleId}`,
    articleLikes: (articleId: string | number) => `/secure/articles/${articleId}/likes`,
    articleComments: (articleId: string | number) => `/articles/${articleId}/comments`,
    createArticleComment: (articleId: string | number) => `/secure/articles/${articleId}/comments`,
    commentManagement: (commentId: string | number) => `/secure/comments/${commentId}`,
    chatbotAsk: "/secure/ask",
};

export default endpoints;